#!/bin/sh

# Deps:
# gmp-6.1.0.tar.bz2
# isl-0.16.1.tar.bz2
# mpc-1.0.3.tar.gz
# mpfr-3.1.4.tar.bz2

[ -d build ] || mkdir build
cd build
../gcc-11.3.0/configure --prefix=/opt/gcc-11.3 --enable-languages=c,c++ \
    --disable-multilib --disable-libstdcxx-pch --enable-lto
# --disable-symvers
