#!/bin/sh

[ -d build ] || mkdir build
cd build
../gcc-7.2.0/configure --prefix=/opt/gcc-7.2 --enable-languages=c,c++ \
    --disable-multilib --disable-libstdcxx-pch --enable-lto
# --disable-symvers
